language: scala
scala:
   - 2.10.5
   - 2.11.6
script:
  - sbt ++$TRAVIS_SCALA_VERSION build
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION publish-snapshot
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
after_success:
  - pip install --user codecov && codecov
